repos:
- repo: local
  hooks:
    - id: nox
      name: nox
      files: ^.*\.py$
      language: python
      entry: poetry run nox
      types: [python]
      stages: [push]
      pass_filenames: false
