repos:
- repo: local
  hooks:
    - id: nox
      name: nox
      files: ^.*\.py$
      language: python
      entry: nox
      types: [python]
      # stages: [pre-commit, push]
      pass_filenames: false
