# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0
  macos: circleci/macos@2.3.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test-linux:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-and-test-macos:
    macos:
      xcode: 14.1.0

    steps:
      # Commands will execute in macOS container
      # with Xcode 12.5.1 installed
      - run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
      - run: cd ~/.pyenv && src/configure && make -C src
      - run: echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      - run: echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
      - run: echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      # - run: echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
      # - run: echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
      # - run: echo 'eval "$(pyenv init -)"' >> ~/.zshrc
      # - run: source ~/.zshrc
      - run: source ~/.bashrc && pyenv install 3.10.8 && pyenv global 3.10.8 3.10.8 3.10.8

  build-and-test-windows:
    executor:
      name: win/default
    steps:
      - checkout

      - run: "choco install -y python3 --version=3.10.8"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test-linux
      - build-and-test-macos
      - build-and-test-windows


